language: go
sudo: required

services:
  - docker

env:
  matrix:
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.7.*"

before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cli
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

install:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
  - bin/phpunit

after_script:
  - sudo cat /var/log/upstart/docker.log
